[package]
name = "pyne"
version = "0.2.1"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clipboard = "0.5.0"
once_cell = "1.19.0"
ratatui = "0.28.1"
ropey = "1.6.1"
unicode-width = "0.1.13"
uuid = { version = "1.10.0", features = ["v4"] }
